# Build template for prometheus-exporter containers
# Uses Kaniko to build Docker images and push to Harbor
#
# Key difference from Media-Streaming/P2-Apps build templates:
# This repo IS the source code, so the Dockerfile uses COPY (not git clone)
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: build-prometheus-exporter
  namespace: argo
spec:
  # Disable Linkerd for workflow pods - sidecars block Argo completion detection
  podMetadata:
    annotations:
      linkerd.io/inject: disabled
  # 30 minutes - Go builds are fast
  activeDeadlineSeconds: 1800
  # Clean up pods on successful workflow completion (keeps failed pods for debugging)
  podGC:
    strategy: OnWorkflowSuccess
  entrypoint: build-and-push
  arguments:
    parameters:
      - name: app
        description: "App to build (prometheus-exporter)"
      - name: version
        description: "Commit SHA to tag the image with"
      - name: dockerfile-path
        description: "Path to Dockerfile relative to repo root (e.g., builds/prometheus-exporter/Dockerfile)"
      - name: harbor-project
        description: "Harbor project to store the image"
        default: "security"
      - name: repo
        default: "509-Digital/prometheus-exporter"

  # Volumes available to all templates
  volumes:
    - name: registry-credentials
      secret:
        secretName: harbor-registry-credentials-plain
    - name: github-app-key
      secret:
        secretName: github-app-credentials
    - name: scripts
      configMap:
        name: argo-workflow-scripts
        defaultMode: 0755
    - name: workspace
      emptyDir:
        sizeLimit: 1Gi
    - name: kaniko-scratch
      emptyDir:
        sizeLimit: 1Gi

  templates:
    - name: build-and-push
      dag:
        tasks:
          - name: get-token
            template: github-app-token
          - name: clone-and-build
            template: clone-and-build
            dependencies: [get-token]
            arguments:
              parameters:
                - name: git-token
                  value: "{{tasks.get-token.outputs.result}}"

    - name: github-app-token
      script:
        image: harbor.509.digital/proxy-docker-hub/library/alpine:3.23
        command: [sh, -c]
        source: |
          apk add --no-cache openssl curl jq > /dev/null 2>&1
          /scripts/github-app-token.sh
        volumeMounts:
          - name: github-app-key
            mountPath: /github-app
            readOnly: true
          - name: scripts
            mountPath: /scripts
            readOnly: true
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi

    - name: clone-and-build
      activeDeadlineSeconds: 1800
      inputs:
        parameters:
          - name: git-token
      initContainers:
        # Generate docker config.json from registry credentials
        - name: generate-docker-config
          image: harbor.509.digital/proxy-docker-hub/library/alpine:3.23
          command: [sh, -c]
          args:
            - |
              set -e
              HARBOR_USER=$(cat /credentials/username)
              HARBOR_PASS=$(cat /credentials/password)
              HARBOR_AUTH=$(printf '%s:%s' "$HARBOR_USER" "$HARBOR_PASS" | base64 | tr -d '\n')
              mkdir -p /workspace/.docker
              printf '{"auths":{"harbor-core.harbor.svc.cluster.local":{"auth":"%s"},"harbor.509.digital":{"auth":"%s"}}}' "$HARBOR_AUTH" "$HARBOR_AUTH" > /workspace/.docker/config.json
          volumeMounts:
            - name: registry-credentials
              mountPath: /credentials
              readOnly: true
            - name: workspace
              mountPath: /workspace
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 50m
              memory: 32Mi
        # Clone the repo and checkout the specific commit
        # Unlike Media-Streaming/P2-Apps, this repo IS the source code —
        # we must build the exact commit that triggered the workflow
        - name: git-clone
          image: harbor.509.digital/proxy-docker-hub/alpine/git:2.52.0
          command: [sh, -c]
          args:
            - |
              set -e
              rm -rf /workspace/src
              git clone --depth 50 https://x-access-token:{{inputs.parameters.git-token}}@github.com/{{workflow.parameters.repo}}.git /workspace/src
              cd /workspace/src
              git checkout {{workflow.parameters.version}}
          volumeMounts:
            - name: workspace
              mountPath: /workspace
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
      container:
        image: gcr.io/kaniko-project/executor:v1.24.0
        args:
          - --dockerfile=/workspace/src/{{workflow.parameters.dockerfile-path}}
          - --context=/workspace/src
          # Use internal Harbor service to bypass Traefik rate limiting
          - --destination=harbor-core.harbor.svc.cluster.local/{{workflow.parameters.harbor-project}}/{{workflow.parameters.app}}:{{workflow.parameters.version}}
          - --destination=harbor-core.harbor.svc.cluster.local/{{workflow.parameters.harbor-project}}/{{workflow.parameters.app}}:latest
          - --cache=true
          - --cache-repo=harbor-core.harbor.svc.cluster.local/cache/{{workflow.parameters.app}}
          # Allow HTTP for internal cluster communication
          - --insecure-registry=harbor-core.harbor.svc.cluster.local
          # Pass both VERSION and COMMIT_SHA - Dockerfile uses whichever it needs
          - --build-arg=VERSION={{workflow.parameters.version}}
          - --build-arg=COMMIT_SHA={{workflow.parameters.version}}
          - --build-arg=TARGETARCH=amd64
        volumeMounts:
          - name: workspace
            mountPath: /workspace
          - name: kaniko-scratch
            mountPath: /scratch
        env:
          - name: DOCKER_CONFIG
            value: /workspace/.docker
          - name: TMPDIR
            value: /scratch
        resources:
          requests:
            cpu: 1
            memory: 2Gi
          limits:
            cpu: 8
            memory: 12Gi
