# Argo Events Sensor for prometheus-exporter container builds
# Triggers on pushes to prometheus-exporter main branch
# Submits the prometheus-exporter-build-dispatcher workflow
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: prometheus-exporter-build
  namespace: argo-events
spec:
  # NOTE: argo-events images run as root by default (UID 0).
  # Non-root not yet supported - see https://github.com/argoproj/argo-events/issues/3784
  template:
    container:
      resources:
        requests:
          cpu: 25m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
  dependencies:
    - name: github-push-prometheus-exporter
      eventSourceName: github
      eventName: push
      filters:
        data:
          - path: body.repository.name
            type: string
            value:
              - "prometheus-exporter"
        # Only trigger on pushes to main branch
        script: |
          return event.body.ref == "refs/heads/main"
  triggers:
    # Trigger dispatcher workflow that handles building changed apps
    - template:
        name: prometheus-exporter-build-dispatcher
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: prometheus-exporter-build-dispatch-
                namespace: argo
              spec:
                workflowTemplateRef:
                  name: prometheus-exporter-build-dispatcher
                arguments:
                  parameters:
                    - name: commit-sha
                      value: ""
                    - name: commit-message
                      value: ""
                    - name: repo
                      value: "509-Digital/prometheus-exporter"
          parameters:
            - src:
                dependencyName: github-push-prometheus-exporter
                dataKey: body.after
              dest: spec.arguments.parameters.0.value
              operation: overwrite
            - src:
                dependencyName: github-push-prometheus-exporter
                dataKey: body.head_commit.message
              dest: spec.arguments.parameters.1.value
              operation: overwrite
